### ISSUE TITLE
Default `testSchema.graphql` throws [Invalid default value of argument 'clauses']

### ISSUE THREAD

**Issue by KyleU** [OlegIlyenko/graphql-gateway#1]
Default `run` action loads the test schema, but it doesn't start correctly:

```
13:39:37.554 ERROR s.g.s.SchemaLoader - Can't create the schema from files: /.../graphql-gateway/testSchema.graphql. Schema does not pass validation. Violations:

Invalid default value of argument 'clauses' in field 'report' defined in output type 'Event'. Field 'Event.report.[clauses]' has wrong value: Invalid value.

Invalid default value of argument 'clauses' in field 'report' defined in output type 'TimeSlot'. Field 'TimeSlot.report.[clauses]' has wrong value: Invalid value.

Invalid default value of argument 'clauses' in field 'report' defined in output type 'Host'. Field 'Host.report.[clauses]' has wrong value: Invalid value.
```

**Comment by OlegIlyenko** [comment]
Thanks for reporting this! Looks like the Universe GraphQl schema has changed a bit. I checked it. Turns out they introduced a new scalar type `JSON` and the default value is not compliant with the GraphQL spec (as far as I can tell). Here is the relevant introspection part:

```json
{
  "defaultValue" : "[]",
  "description" : "array of {key: value} or 'string' where clauses",
  "name" : "clauses",
  "type" : {
    "kind" : "SCALAR",
    "name" : "JSON",
    "ofType" : null
  }
}
```

`"[]"` is not valid default value. if JSON is represented as a sting literal, it probably should be something like `"\"[]\""`.

**Comment by OlegIlyenko** [comment]
I updated the example ans now using different schema (Deutsche Bahn GraphQL API 🚂🚃🚃🚃🚃). looks better now :)

![screenshot_060518_103017_pm](https://user-images.githubusercontent.com/156569/41001007-0c354426-6910-11e8-9da2-fa04e434a572.jpg)
