### ISSUE TITLE
Define schema with .graphql files and the "sangria" way

### ISSUE THREAD

**Issue by santilytics** [OlegIlyenko/graphql-gateway#7]
I've started working with graphql in scala directly with this gateway. I think this has narrowed my view on how to use this tool since I handle most of the domain logic through directives.

Is there a way to use the `.graphql` files along using `ObjectType` (even object type derivation) to define the schema?

**Comment by OlegIlyenko** [comment]
Sure, you probably would be interested to check schema extension. There is an example of it in the docs: https://sangria-graphql.org/learn/#schema-materialization-example

In particular this part:

```scala
val schema = staticSchema.extend(extensions, builder)
```

This extends existing schema (defined in the normal scala code with `ObjectType`, etc.) with extension SDL (which might be loaded from `*.graphql` file). 

Is it something that might help in your case?

**Comment by santilytics** [comment]
I believe this is exactly what I need!
One more question, since I started with the schema defined as a set of SDL files, is it possible to extend from SDL just as easily or would I need to define my 'scala' schema and then extend with the files and the builder?

**Comment by OlegIlyenko** [comment]
Since types defined directly are type safe and cross-referenced I think it would be hard to do it other way around as you have described. Though it is still possible. For example, with resolver-based materializer you can provide a list of addition GraphQL types with [`AdditionalTypes`](https://github.com/sangria-graphql/sangria/blob/master/src/main/scala/sangria/schema/AstSchemaResolver.scala#L11) which you can define either with SDL or in scala with `ObjectType` & co. So you can start with SDL and then add extra types defined in scala.

**Comment by santilytics** [comment]
This should help, thanks for your time!
